package core

import (
	"fmt"
	"io/ioutil"
	"os"
	"strconv"
	"strings"

	"github.com/signintech/gopdf"
	fontcore "github.com/signintech/gopdf/fontmaker/core"
)

type fontMetrics struct {
	ascenderPerEm   float64 // ascender / unitsPerEm
	descenderPerEm  float64 // descender / unitsPerEm (negative)
	spaceWidthPerEm float64 // space glyph width / unitsPerEm
}

type FontMap struct {
	FontName string
	FileName string
	Data     []byte // Bytes data of font file, will be converted to temp file if provided
}

// Converter is a bridge to third-party gopdf.
// The content generated by the user by calling a simple interface
// is converted from pdf to complex content, and finally a pdf file
// is generated.
type Converter struct {
	pdf *gopdf.GoPdf

	// Atomic unit, multiple cells are finally combined into a PDF file
	atomicCells []string

	// unit is the scale from user-facing numeric cells to PDF points. Only pt is supported (1:1).
	unit  float64
	fonts []*FontMap // fonts

	linew     float64  // line width
	lastFont  string   // last used font name
	tempFonts []string // temporary font files created from bytes data, used for cleanup

	fontMetrics map[string]*fontMetrics // key: font family name
}

// GetAtomicCells, get atomicCells
func (convert *Converter) GetAutomicCells() []string {
	cells := make([]string, len(convert.atomicCells))
	copy(cells, convert.atomicCells)
	return cells
}

// SetAtomicCells, set atomicCells (use caution)
func (convert *Converter) SetAutomicCells(cells []string) {
	convert.atomicCells = cells
}

// Add a atomicCell to atomicCells
func (convert *Converter) AddAtomicCell(cell string) {
	if strings.HasPrefix(cell, "F|") {
		if cell == convert.lastFont {
			return
		}

		convert.lastFont = cell
	}

	convert.atomicCells = append(convert.atomicCells, cell)
}

// ReadFile parse file content to  atomicCells
// Generate pdf files for text content from already saved atomicCells,
// generally used for debugging.
func (convert *Converter) ReadFile(fileName string) error {
	buf, err := ioutil.ReadFile(fileName)
	if err != nil {
		return err
	}
	text := strings.Replace(string(buf), "\r", "", -1)
	var UTF8_BOM = []byte{239, 187, 191}
	if text[0:3] == string(UTF8_BOM) {
		text = text[3:]
	}
	convert.atomicCells = strings.Split(text, "\n")
	return nil
}

// Generate a pdf file of the content recorded in atomicCells.
func (convert *Converter) Execute() {
	lines := convert.atomicCells
	for _, line := range lines {
		elements := strings.Split(line, "|")
		switch elements[0] {
		case "P":
			convert.Page(line, elements) // pdf start
		case "NP":
			convert.NewPage(line, elements) // new page
		case "F":
			convert.Font(line, elements) // font
		case "TC":
			convert.TextColor(line, elements) // text color
		case "LC":
			convert.LineColor(line, elements) // line color
		case "BC":
			convert.BackgroundColor(line, elements) // backgroup color
		case "GF", "GS":
			convert.Grey(line, elements) //
		case "C", "CL", "CR":
			convert.Cell(line, elements) // cell contens. third lib basic content
		case "L", "LV", "LH", "LT":
			convert.Line(line, elements) // one row
		case "R":
			convert.Rect(line, elements) // rectangle
		case "O":
			convert.Oval(line, elements) // oval
		case "I":
			convert.Image(line, elements) // image
		case "M":
			convert.Margin(line, elements) // margin, can adjust content postion
		case "EL":
			convert.ExternalLink(line, elements) // outer link
		case "ILA":
			convert.InternalLinkAnchor(line, elements) // inner link anchor
		case "ILL":
			convert.InternalLinkLink(line, elements) // inner link linker
		default:
			if len(line) > 0 && line[0:1] != "v" {
				fmt.Println("skip:" + line + ":")
			}
		}
	}
}

// add fonts
func (convert *Converter) AddFont() {
	if convert.fontMetrics == nil {
		convert.fontMetrics = make(map[string]*fontMetrics)
	}
	for _, font := range convert.fonts {
		fileName := font.FileName
		// If Data is provided, create a temporary file
		if len(font.Data) > 0 {
			tempFile, err := ioutil.TempFile("", "gopdf_font_*.ttf")
			if err != nil {
				panic("failed to create temp font file: " + err.Error())
			}
			defer tempFile.Close()

			_, err = tempFile.Write(font.Data)
			if err != nil {
				panic("failed to write temp font file: " + err.Error())
			}

			fileName = tempFile.Name()
			convert.tempFonts = append(convert.tempFonts, fileName)
		}

		err := convert.pdf.AddTTFFont(font.FontName, fileName)
		if err != nil {
			panic("font file:" + fileName + " not found, err:" + err.Error())
		}

		// parse font metrics
		var parser fontcore.TTFParser
		if err := parser.Parse(fileName); err == nil {
			units := float64(parser.UnitsPerEm())
			if units == 0 {
				units = 1000
			}
			m := &fontMetrics{
				ascenderPerEm:   float64(parser.Ascender()) / units,
				descenderPerEm:  float64(parser.Descender()) / units,
				spaceWidthPerEm: convert.parseSpaceWidth(&parser) / units,
			}
			convert.fontMetrics[font.FontName] = m
		}
	}
}

func (convert *Converter) parseSpaceWidth(parser *fontcore.TTFParser) float64 {
	chars := parser.Chars()
	glyphID, ok := chars[32]
	if !ok {
		return 250 // typical default space width in font units
	}
	widths := parser.Widths()
	idx := int(glyphID)
	if idx < len(widths) {
		return float64(widths[idx])
	}
	if len(widths) > 0 {
		return float64(widths[len(widths)-1])
	}
	return 250
}

func (convert *Converter) GetFontMetrics(family string, size float64) (ascender, descender float64) {
	if m, ok := convert.fontMetrics[family]; ok {
		return m.ascenderPerEm * size, m.descenderPerEm * size
	}
	// fallback: typical proportions
	return size * 0.8, size * -0.2
}

func (convert *Converter) GetSpaceWidth(family string, size float64) float64 {
	if m, ok := convert.fontMetrics[family]; ok {
		return m.spaceWidthPerEm * size
	}
	return size * 0.25
}

// Page
// [P, pt, A4, P|L]
// Only "pt" (PDF points) is accepted for elements[1]. P|L is portrait or landscape.
func (convert *Converter) Page(line string, elements []string) {
	convert.pdf = new(gopdf.GoPdf)

	checkLength(line, elements, 4)
	switch elements[2] {
	/* A0 ~ A5 Paper pixel representation:
	'A0': [2383.94, 3370.39],
	'A1': [1683.78, 2383.94],
	'A2': [1190.55, 1683.78],
	'A3': [841.89, 1190.55],
	'A4': [595.28, 841.89],
	'A5': [419.53, 595.28],
	*/
	case "A3":
		config := defaultConfigs["A3"]
		convert.setunit(elements[1])
		if elements[3] == "P" {
			convert.start(config.width, config.height)
		} else if elements[3] == "L" {
			convert.start(config.height, config.width)
		} else {
			panic("Page Orientation accept P or L")
		}
	case "A4":
		config := defaultConfigs["A4"]
		convert.setunit(elements[1])
		if elements[3] == "P" {
			convert.start(config.width, config.height)
		} else if elements[3] == "L" {
			convert.start(config.height, config.width)
		} else {
			panic("Page Orientation accept P or L")
		}
	case "LTR":
		config := defaultConfigs["LTR"]
		convert.setunit(elements[1])
		if elements[3] == "P" {
			convert.start(config.width, config.height)
		} else if elements[3] == "L" {
			convert.start(config.height, config.width)
		} else {
			panic("Page Orientation accept P or L")
		}
	default:
		panic("This size not supported yet:" + elements[2])
	}
	convert.AddFont()
	convert.pdf.AddPage()
}

// setunit accepts only "pt" (PDF points). Raw cell streams must not use mm or in.
func (convert *Converter) setunit(unit string) {
	switch unit {
	case "pt":
		convert.unit = 1
	default:
		panic("only pt (PDF points) is supported, got: " + unit)
	}
}

// add new page
func (convert *Converter) NewPage(line string, elements []string) {
	convert.pdf.AddPage()
}

// Set PDF file configuration information (unit, page size)
func (convert *Converter) start(w float64, h float64) {
	convert.pdf.Start(gopdf.Config{
		Unit:     gopdf.Unit_PT,
		PageSize: gopdf.Rect{W: w, H: h},
	}) // 595.28, 841.89 = A4
}

// Set Font used for the current text
// ["", "family", "style", "size"]
// style: "" or "U", ("B", "I")("B" means "Bold", "I" means "Italic", these font self support)
func (convert *Converter) Font(line string, elements []string) {
	checkLength(line, elements, 4)
	size := parseIntPanic(elements[3], line)
	err := convert.pdf.SetFont(elements[1], elements[2], size)
	if err != nil {
		panic(err.Error() + " line;" + line)
	}
}

// Set the gray scale of the stroke Or Set the gray scale of the fill
// ["GF|GS", grayScale]
// grayScale: 0.0 到 1.0
func (convert *Converter) Grey(line string, elements []string) {
	checkLength(line, elements, 2)
	if elements[0] == "GF" {
		convert.pdf.SetGrayFill(parseFloatPanic(elements[1], line))
	}
	if elements[0] == "GS" {
		convert.pdf.SetGrayStroke(parseFloatPanic(elements[1], line))
	}
}

// text color
// ["", R, G, B]
func (convert *Converter) TextColor(line string, elements []string) {
	checkLength(line, elements, 4)
	convert.pdf.SetTextColor(uint8(parseIntPanic(elements[1], line)),
		uint8(parseIntPanic(elements[2], line)),
		uint8(parseIntPanic(elements[3], line)))
}

// line color
// ["", R, G, B]
func (convert *Converter) LineColor(line string, elements []string) {
	checkLength(line, elements, 4)
	convert.pdf.SetStrokeColor(uint8(parseIntPanic(elements[1], line)),
		uint8(parseIntPanic(elements[2], line)),
		uint8(parseIntPanic(elements[3], line)))
}

// backgroup color
func (convert *Converter) BackgroundColor(line string, elements []string) {
	checkLength(line, elements, 12)

	// white line
	convert.pdf.SetStrokeColor(255, 255, 255)

	// set fill backgroup color
	convert.pdf.SetFillColor(uint8(parseIntPanic(elements[5], line)),
		uint8(parseIntPanic(elements[6], line)),
		uint8(parseIntPanic(elements[7], line)))

	convert.pdf.RectFromUpperLeftWithStyle(parseFloatPanic(elements[1], line)*convert.unit,
		parseFloatPanic(elements[2], line)*convert.unit,
		parseFloatPanic(elements[3], line)*convert.unit,
		parseFloatPanic(elements[4], line)*convert.unit, "F")

	// recover origin backgroup color and line color
	convert.pdf.SetFillColor(1, 1, 1)
	convert.pdf.SetStrokeColor(uint8(parseIntPanic(elements[9], line)),
		uint8(parseIntPanic(elements[10], line)),
		uint8(parseIntPanic(elements[11], line)))

	convert.pdf.SetLineType("solid")
	convert.pdf.SetLineWidth(convert.linew * convert.unit)

	x := parseFloatPanic(elements[1], line) * convert.unit
	y := parseFloatPanic(elements[2], line) * convert.unit
	w := parseFloatPanic(elements[3], line) * convert.unit
	h := parseFloatPanic(elements[4], line) * convert.unit

	// Add lines, contains LEFT, TOP, RIGHT, BOTTOM
	lines := elements[8]
	if lines[0] == '1' {
		convert.pdf.Line(x, y, x, y+h)
	}
	if lines[1] == '1' {
		convert.pdf.Line(x, y, x+w, y)
	}
	if lines[2] == '1' {
		convert.pdf.Line(x+w, y, x+w, y+h)
	}
	if lines[3] == '1' {
		convert.pdf.Line(x, y+h, x+w, y+h)
	}
}

// oval
// ["", x1, y1, x2, y2]
func (convert *Converter) Oval(line string, elements []string) {
	checkLength(line, elements, 5)
	convert.pdf.Oval(parseFloatPanic(elements[1], line)*convert.unit,
		parseFloatPanic(elements[2], line)*convert.unit,
		parseFloatPanic(elements[3], line)*convert.unit,
		parseFloatPanic(elements[4], line)*convert.unit)
}

// rectangle
// ["R", x1, y1, x2, y2]
func (convert *Converter) Rect(line string, eles []string) {
	checkLength(line, eles, 5)
	adj := convert.linew * convert.unit * 0.5
	convert.pdf.Line(
		parseFloatPanic(eles[1], line)*convert.unit,
		parseFloatPanic(eles[2], line)*convert.unit+adj,
		parseFloatPanic(eles[3], line)*convert.unit+adj*2,
		parseFloatPanic(eles[2], line)*convert.unit+adj)

	convert.pdf.Line(
		parseFloatPanic(eles[1], line)*convert.unit+adj,
		parseFloatPanic(eles[2], line)*convert.unit,
		parseFloatPanic(eles[1], line)*convert.unit+adj,
		parseFloatPanic(eles[4], line)*convert.unit+adj*2)

	convert.pdf.Line(
		parseFloatPanic(eles[1], line)*convert.unit,
		parseFloatPanic(eles[4], line)*convert.unit+adj,
		parseFloatPanic(eles[3], line)*convert.unit+adj*2,
		parseFloatPanic(eles[4], line)*convert.unit+adj)

	convert.pdf.Line(
		parseFloatPanic(eles[3], line)*convert.unit+adj,
		parseFloatPanic(eles[2], line)*convert.unit,
		parseFloatPanic(eles[3], line)*convert.unit+adj,
		parseFloatPanic(eles[4], line)*convert.unit+adj*2)
}

// image
// ["I", path, x, y, x1, y2]
func (convert *Converter) Image(line string, elements []string) {
	checkLength(line, elements, 6)
	r := new(gopdf.Rect)
	r.W = parseFloatPanic(elements[4], line)*convert.unit - parseFloatPanic(elements[2], line)*convert.unit
	r.H = parseFloatPanic(elements[5], line)*convert.unit - parseFloatPanic(elements[3], line)*convert.unit

	err := convert.pdf.Image(
		elements[1],
		parseFloatPanic(elements[2], line)*convert.unit,
		parseFloatPanic(elements[3], line)*convert.unit,
		r,
	)
	if err != nil {
		panic(err.Error() + " line;" + line)
	}
}

// line
// ["L", x1, y1, x2, y2], Line between any two points
// ["LH", x1, y1, x2], Horizontal line
// ["LV", x1, y2, y2], Vertical line
//
// ["LT", "dashed|dotted|straight", w] Lines with a specific style(dashed,dotted,straight)
// dashed: ----
// dotted: ....
// straight: ___
func (convert *Converter) Line(line string, elements []string) {
	switch elements[0] {
	case "L":
		checkLength(line, elements, 5)
		convert.pdf.Line(
			parseFloatPanic(elements[1], line)*convert.unit,
			parseFloatPanic(elements[2], line)*convert.unit,
			parseFloatPanic(elements[3], line)*convert.unit,
			parseFloatPanic(elements[4], line)*convert.unit,
		)
	case "LH":
		checkLength(line, elements, 4)
		convert.pdf.Line(
			parseFloatPanic(elements[1], line)*convert.unit,
			parseFloatPanic(elements[2], line)*convert.unit,
			parseFloatPanic(elements[3], line)*convert.unit,
			parseFloatPanic(elements[2], line)*convert.unit,
		)
	case "LV":
		checkLength(line, elements, 4)
		convert.pdf.Line(
			parseFloatPanic(elements[1], line)*convert.unit,
			parseFloatPanic(elements[2], line)*convert.unit,
			parseFloatPanic(elements[1], line)*convert.unit,
			parseFloatPanic(elements[3], line)*convert.unit,
		)
	case "LT":
		checkLength(line, elements, 3)
		lineType := elements[1]
		if lineType == "" {
			lineType = "straight"
		}
		convert.pdf.SetLineType(lineType)
		convert.linew = parseFloatPanic(elements[2], line)
		convert.pdf.SetLineWidth(convert.linew * convert.unit)
	}
}

// Clell
// ["C", family, size, x, y, content] // Start writing text from position (x,y)
// ["CL", x, y, content] // Start writing text from position (x,y)
// ["CR", x, y, w, content] // Write text of w length from right to left
func (convert *Converter) Cell(line string, elements []string) {
	switch elements[0] {
	case "C":
		checkLength(line, elements, 6)
		size := parseIntPanic(elements[2], line)
		err := convert.pdf.SetFont(elements[1], "", size)
		if err != nil {
			panic(err.Error() + " line;" + line)
		}
		convert.setPosition(elements[3], elements[4], line)
		err = convert.pdf.Text(elements[5])
		if err != nil {
			panic(err.Error() + " line;" + line)
		}
	case "CL":
		checkLength(line, elements, 4)
		convert.setPosition(elements[1], elements[2], line)
		err := convert.pdf.Text(elements[3])
		if err != nil {
			panic(err.Error() + " line;" + line)
		}
	case "CR":
		checkLength(line, elements, 5)
		tw, err := convert.pdf.MeasureTextWidth(elements[4])
		if err != nil {
			panic(err.Error() + " line;" + line)
		}
		x := parseFloatPanic(elements[1], line) * convert.unit
		y := parseFloatPanic(elements[2], line) * convert.unit
		w := parseFloatPanic(elements[3], line) * convert.unit
		finalx := x + w - tw
		convert.pdf.SetX(finalx)
		convert.pdf.SetY(y)
		err = convert.pdf.Text(elements[4])
		if err != nil {
			panic(err.Error() + " line;" + line)
		}
	}
}

func (convert *Converter) setPosition(x string, y string, line string) {
	convert.pdf.SetX(parseFloatPanic(x, line) * convert.unit)
	convert.pdf.SetY(parseFloatPanic(y, line) * convert.unit)
}

// external link
// ["EL", x, y, w, h, content, link] // Start writing text from (x,y) and add external links
func (convert *Converter) ExternalLink(line string, elements []string) {
	checkLength(line, elements, 7)

	x, y := parseFloatPanic(elements[1], line), parseFloatPanic(elements[2], line)
	w, h := parseFloatPanic(elements[3], line), parseFloatPanic(elements[4], line)

	convert.pdf.SetX(x)
	convert.pdf.SetY(y)

	err := convert.pdf.Text(elements[5])
	if err != nil {
		panic(err.Error() + " line;" + line)
	}
	y1 := y
	if y-h > 0 {
		y1 = y - h
	}
	convert.pdf.AddExternalLink(elements[6], x, y1, w, h)

	convert.pdf.SetX(x + w)
	convert.pdf.SetY(y)
}

// Internal link, anchor
// ["ILA", x, y, w, h, content, anchor]
func (convert *Converter) InternalLinkAnchor(line string, elements []string) {
	checkLength(line, elements, 7)

	x, y := parseFloatPanic(elements[1], line), parseFloatPanic(elements[2], line)
	w, h := parseFloatPanic(elements[3], line), parseFloatPanic(elements[4], line)
	convert.pdf.SetX(x)
	convert.pdf.SetY(y)

	err := convert.pdf.Text(elements[5])
	if err != nil {
		panic(err.Error() + " line;" + line)
	}
	y1 := y
	if y-h > 0 {
		y1 = y - h
	}
	convert.pdf.AddInternalLink(elements[6], x, y1, w, h)

	convert.pdf.SetX(x + w)
	convert.pdf.SetY(y)
}

// Internal link, link
// ["ILL", x, y, w  content, anchor]
func (convert *Converter) InternalLinkLink(line string, elements []string) {
	checkLength(line, elements, 6)

	convert.pdf.SetX(parseFloatPanic(elements[1], line))
	convert.pdf.SetY(parseFloatPanic(elements[2], line))

	err := convert.pdf.Text(elements[4])
	if err != nil {
		panic(err.Error() + " line;" + line)
	}
	convert.pdf.SetAnchor(elements[5])

	convert.pdf.SetX(parseFloatPanic(elements[1], line) + parseFloatPanic(elements[3], line))
	convert.pdf.SetY(parseFloatPanic(elements[2], line))
}

func (convert *Converter) Margin(line string, eles []string) {
	checkLength(line, eles, 3)
	top := parseFloatPanic(eles[1], line)
	left := parseFloatPanic(eles[2], line)
	if top != 0.0 {
		convert.pdf.SetTopMargin(top)
	}

	if left != 0.0 {
		convert.pdf.SetLeftMargin(left)
	}
}

func (convert *Converter) GetXY() (x, y float64) {
	return convert.pdf.GetX(), convert.pdf.GetY()
}

func (convert *Converter) MeasureTextWidth(text string) float64 {
	w, err := convert.pdf.MeasureTextWidth(text)
	if err != nil {
		panic(err)
	}

	return w
}

func (convert *Converter) SetFont(family, style string, size int) {
	err := convert.pdf.SetFont(family, style, size)
	if err != nil {
		panic(err.Error())
	}
}

func (convert *Converter) NoCompression() {
	convert.pdf.SetNoCompression()
}

func (convert *Converter) WritePdf(filepath string) {
	err := convert.pdf.WritePdf(filepath)
	if err != nil {
		panic(err.Error())
	}
}

func (convert *Converter) CompressLevel(level int) {
	convert.pdf.SetCompressLevel(level)
}

func (convert *Converter) GetBytesPdf() (ret []byte) {
	return convert.pdf.GetBytesPdf()
}

// CleanupTempFonts removes all temporary font files created from bytes data
func (convert *Converter) CleanupTempFonts() {
	for _, filePath := range convert.tempFonts {
		err := os.Remove(filePath)
		if err != nil {
			fmt.Printf("Warning: failed to remove temp font file %s: %v\n", filePath, err)
		}
	}
	convert.tempFonts = nil
}

func checkLength(line string, eles []string, no int) {
	if len(eles) < no {
		panic("Column short:" + line)
	}
}

func parseIntPanic(num string, line string) int {
	i, err := strconv.Atoi(num)
	if err != nil {
		panic(num + " not Integer :" + line)
	}
	return i
}

func parseFloatPanic(num string, line string) float64 {
	if num == "" {
		return 0
	}
	f, err := strconv.ParseFloat(num, 64)
	if err != nil {
		panic(num + " not Numeric :" + line)
	}
	return f
}
