package core

import (
	"fmt"
	"io/ioutil"
	"os"
	"strconv"
	"strings"

	"github.com/signintech/gopdf"
	fontcore "github.com/signintech/gopdf/fontmaker/core"
)

type fontMetrics struct {
	ascenderPerEm   float64 // ascender / unitsPerEm
	descenderPerEm  float64 // descender / unitsPerEm (negative)
	spaceWidthPerEm float64 // space glyph width / unitsPerEm
}

type FontMap struct {
	FontName string
	FileName string
	Data     []byte // Bytes data of font file, will be converted to temp file if provided
}

// Converter is a bridge to third-party gopdf.
// The content generated by the user by calling a simple interface
// is converted from pdf to complex content, and finally a pdf file
// is generated.
type Converter struct {
	pdf *gopdf.GoPdf

	// Atomic unit, multiple cells are finally combined into a PDF file
	atomicCells []string

	// unit is the scale from user-facing numeric cells to PDF points. Only pt is supported (1:1).
	unit  float64
	fonts []*FontMap // fonts

	linew     float64  // line width
	lastFont  string   // last used font name
	tempFonts []string // temporary font files created from bytes data, used for cleanup

	fontMetrics map[string]*fontMetrics // key: font family name
}

// GetAtomicCells returns a copy of the atomic instruction lines.
func (convert *Converter) GetAtomicCells() []string {
	cells := make([]string, len(convert.atomicCells))
	copy(cells, convert.atomicCells)
	return cells
}

// Deprecated: typo; use GetAtomicCells.
func (convert *Converter) GetAutomicCells() []string {
	return convert.GetAtomicCells()
}

// SetAtomicCells replaces the atomic instruction stream (use with caution).
func (convert *Converter) SetAtomicCells(cells []string) {
	convert.atomicCells = cells
}

// Deprecated: typo; use SetAtomicCells.
func (convert *Converter) SetAutomicCells(cells []string) {
	convert.SetAtomicCells(cells)
}

// AddAtomicCell appends one atomic Cell line.
func (convert *Converter) AddAtomicCell(cell string) {
	if strings.HasPrefix(cell, "F|") {
		if cell == convert.lastFont {
			return
		}

		convert.lastFont = cell
	}

	convert.atomicCells = append(convert.atomicCells, cell)
}

// ReadFile parses file content into atomicCells (for debugging or replay).
func (convert *Converter) ReadFile(fileName string) error {
	buf, err := ioutil.ReadFile(fileName)
	if err != nil {
		return err
	}
	text := strings.Replace(string(buf), "\r", "", -1)
	var utf8bom = []byte{239, 187, 191}
	if len(text) >= 3 && text[0:3] == string(utf8bom) {
		text = text[3:]
	}
	convert.atomicCells = strings.Split(text, "\n")
	return nil
}

// Execute renders the accumulated atomic Cells into convert.pdf.
func (convert *Converter) Execute() error {
	lines := convert.atomicCells
	for _, line := range lines {
		elements := strings.Split(line, "|")
		var err error
		if len(elements) == 0 {
			continue
		}
		switch elements[0] {
		case "P":
			err = convert.Page(line, elements)
		case "NP":
			err = convert.NewPage(line, elements)
		case "F":
			err = convert.Font(line, elements)
		case "TC":
			err = convert.TextColor(line, elements)
		case "LC":
			err = convert.LineColor(line, elements)
		case "BC":
			err = convert.BackgroundColor(line, elements)
		case "GF", "GS":
			err = convert.Grey(line, elements)
		case "C", "CL", "CR":
			err = convert.Cell(line, elements)
		case "L", "LV", "LH", "LT":
			err = convert.Line(line, elements)
		case "R":
			err = convert.Rect(line, elements)
		case "O":
			err = convert.Oval(line, elements)
		case "I":
			err = convert.Image(line, elements)
		case "M":
			err = convert.Margin(line, elements)
		case "EL":
			err = convert.ExternalLink(line, elements)
		case "ILA":
			err = convert.InternalLinkAnchor(line, elements)
		case "ILL":
			err = convert.InternalLinkLink(line, elements)
		default:
			if len(line) > 0 && line[0:1] != "v" {
				fmt.Println("skip:" + line + ":")
			}
		}
		if err != nil {
			return err
		}
	}
	return nil
}

func (convert *Converter) AddFont() error {
	if convert.fontMetrics == nil {
		convert.fontMetrics = make(map[string]*fontMetrics)
	}
	for _, font := range convert.fonts {
		fileName := font.FileName
		if len(font.Data) > 0 {
			tempFile, err := ioutil.TempFile("", "gopdf_font_*.ttf")
			if err != nil {
				return fmt.Errorf("create temp font file: %w", err)
			}
			_, err = tempFile.Write(font.Data)
			fn := tempFile.Name()
			if cerr := tempFile.Close(); cerr != nil {
				os.Remove(fn)
				if err != nil {
					return fmt.Errorf("write temp font file: %w", err)
				}
				return fmt.Errorf("close temp font file: %w", cerr)
			}
			if err != nil {
				os.Remove(fn)
				return fmt.Errorf("write temp font file: %w", err)
			}
			fileName = fn
			convert.tempFonts = append(convert.tempFonts, fileName)
		}

		if err := convert.pdf.AddTTFFont(font.FontName, fileName); err != nil {
			return fmt.Errorf("add TTF font %q from %s: %w", font.FontName, fileName, err)
		}

		var parser fontcore.TTFParser
		if err := parser.Parse(fileName); err == nil {
			units := float64(parser.UnitsPerEm())
			if units == 0 {
				units = 1000
			}
			m := &fontMetrics{
				ascenderPerEm:   float64(parser.Ascender()) / units,
				descenderPerEm:  float64(parser.Descender()) / units,
				spaceWidthPerEm: convert.parseSpaceWidth(&parser) / units,
			}
			convert.fontMetrics[font.FontName] = m
		}
	}
	return nil
}

func (convert *Converter) parseSpaceWidth(parser *fontcore.TTFParser) float64 {
	chars := parser.Chars()
	glyphID, ok := chars[32]
	if !ok {
		return 250
	}
	widths := parser.Widths()
	idx := int(glyphID)
	if idx < len(widths) {
		return float64(widths[idx])
	}
	if len(widths) > 0 {
		return float64(widths[len(widths)-1])
	}
	return 250
}

func (convert *Converter) GetFontMetrics(family string, size float64) (ascender, descender float64) {
	if m, ok := convert.fontMetrics[family]; ok {
		return m.ascenderPerEm * size, m.descenderPerEm * size
	}
	return size * 0.8, size * -0.2
}

func (convert *Converter) GetSpaceWidth(family string, size float64) float64 {
	if m, ok := convert.fontMetrics[family]; ok {
		return m.spaceWidthPerEm * size
	}
	return size * 0.25
}

// Page
// [P, pt, A4, P|L]
// Only "pt" (PDF points) is accepted for elements[1]. P|L is portrait or landscape.
func (convert *Converter) Page(line string, elements []string) error {
	convert.pdf = new(gopdf.GoPdf)

	if err := checkLength(line, elements, 4); err != nil {
		return err
	}
	switch elements[2] {
	case "A3":
		config := defaultConfigs["A3"]
		if err := convert.setunit(elements[1]); err != nil {
			return err
		}
		if elements[3] == "P" {
			convert.start(config.width, config.height)
		} else if elements[3] == "L" {
			convert.start(config.height, config.width)
		} else {
			return fmt.Errorf("page orientation must be P or L: %s", line)
		}
	case "A4":
		config := defaultConfigs["A4"]
		if err := convert.setunit(elements[1]); err != nil {
			return err
		}
		if elements[3] == "P" {
			convert.start(config.width, config.height)
		} else if elements[3] == "L" {
			convert.start(config.height, config.width)
		} else {
			return fmt.Errorf("page orientation must be P or L: %s", line)
		}
	case "LTR":
		config := defaultConfigs["LTR"]
		if err := convert.setunit(elements[1]); err != nil {
			return err
		}
		if elements[3] == "P" {
			convert.start(config.width, config.height)
		} else if elements[3] == "L" {
			convert.start(config.height, config.width)
		} else {
			return fmt.Errorf("page orientation must be P or L: %s", line)
		}
	default:
		return fmt.Errorf("page size not supported: %s in %s", elements[2], line)
	}
	if err := convert.AddFont(); err != nil {
		return err
	}
	convert.pdf.AddPage()
	return nil
}

func (convert *Converter) setunit(unit string) error {
	switch unit {
	case "pt":
		convert.unit = 1
		return nil
	default:
		return fmt.Errorf("only pt (PDF points) is supported, got %q", unit)
	}
}

func (convert *Converter) NewPage(line string, elements []string) error {
	convert.pdf.AddPage()
	return nil
}

func (convert *Converter) start(w float64, h float64) {
	convert.pdf.Start(gopdf.Config{
		Unit:     gopdf.Unit_PT,
		PageSize: gopdf.Rect{W: w, H: h},
	})
}

// Font sets the current PDF font from a cell record.
func (convert *Converter) Font(line string, elements []string) error {
	if err := checkLength(line, elements, 4); err != nil {
		return err
	}
	size, err := parseIntCell(elements[3], line)
	if err != nil {
		return err
	}
	if err := convert.pdf.SetFont(elements[1], elements[2], size); err != nil {
		return fmt.Errorf("%w; line %s", err, line)
	}
	return nil
}

func (convert *Converter) Grey(line string, elements []string) error {
	if err := checkLength(line, elements, 2); err != nil {
		return err
	}
	g, err := parseFloatCell(elements[1], line)
	if err != nil {
		return err
	}
	if elements[0] == "GF" {
		convert.pdf.SetGrayFill(g)
	}
	if elements[0] == "GS" {
		convert.pdf.SetGrayStroke(g)
	}
	return nil
}

func (convert *Converter) TextColor(line string, elements []string) error {
	if err := checkLength(line, elements, 4); err != nil {
		return err
	}
	r1, err := parseIntCell(elements[1], line)
	if err != nil {
		return err
	}
	r2, err := parseIntCell(elements[2], line)
	if err != nil {
		return err
	}
	r3, err := parseIntCell(elements[3], line)
	if err != nil {
		return err
	}
	convert.pdf.SetTextColor(uint8(r1), uint8(r2), uint8(r3))
	return nil
}

func (convert *Converter) LineColor(line string, elements []string) error {
	if err := checkLength(line, elements, 4); err != nil {
		return err
	}
	r1, err := parseIntCell(elements[1], line)
	if err != nil {
		return err
	}
	r2, err := parseIntCell(elements[2], line)
	if err != nil {
		return err
	}
	r3, err := parseIntCell(elements[3], line)
	if err != nil {
		return err
	}
	convert.pdf.SetStrokeColor(uint8(r1), uint8(r2), uint8(r3))
	return nil
}

func (convert *Converter) BackgroundColor(line string, elements []string) error {
	if err := checkLength(line, elements, 12); err != nil {
		return err
	}
	convert.pdf.SetStrokeColor(255, 255, 255)

	e5, err := parseIntCell(elements[5], line)
	if err != nil {
		return err
	}
	e6, err := parseIntCell(elements[6], line)
	if err != nil {
		return err
	}
	e7, err := parseIntCell(elements[7], line)
	if err != nil {
		return err
	}
	convert.pdf.SetFillColor(uint8(e5), uint8(e6), uint8(e7))

	x1, err := parseFloatCell(elements[1], line)
	if err != nil {
		return err
	}
	x2, err := parseFloatCell(elements[2], line)
	if err != nil {
		return err
	}
	x3, err := parseFloatCell(elements[3], line)
	if err != nil {
		return err
	}
	x4, err := parseFloatCell(elements[4], line)
	if err != nil {
		return err
	}
	convert.pdf.RectFromUpperLeftWithStyle(x1*convert.unit, x2*convert.unit, x3*convert.unit, x4*convert.unit, "F")

	e9, err := parseIntCell(elements[9], line)
	if err != nil {
		return err
	}
	e10, err := parseIntCell(elements[10], line)
	if err != nil {
		return err
	}
	e11, err := parseIntCell(elements[11], line)
	if err != nil {
		return err
	}
	convert.pdf.SetFillColor(1, 1, 1)
	convert.pdf.SetStrokeColor(uint8(e9), uint8(e10), uint8(e11))

	convert.pdf.SetLineType("solid")
	convert.pdf.SetLineWidth(convert.linew * convert.unit)

	x := x1 * convert.unit
	y := x2 * convert.unit
	w := x3 * convert.unit
	h := x4 * convert.unit

	lines := elements[8]
	if lines[0] == '1' {
		convert.pdf.Line(x, y, x, y+h)
	}
	if lines[1] == '1' {
		convert.pdf.Line(x, y, x+w, y)
	}
	if lines[2] == '1' {
		convert.pdf.Line(x+w, y, x+w, y+h)
	}
	if lines[3] == '1' {
		convert.pdf.Line(x, y+h, x+w, y+h)
	}
	return nil
}

func (convert *Converter) Oval(line string, elements []string) error {
	if err := checkLength(line, elements, 5); err != nil {
		return err
	}
	fs := make([]float64, 4)
	for i := 0; i < 4; i++ {
		v, err := parseFloatCell(elements[1+i], line)
		if err != nil {
			return err
		}
		fs[i] = v * convert.unit
	}
	convert.pdf.Oval(fs[0], fs[1], fs[2], fs[3])
	return nil
}

func (convert *Converter) Rect(line string, eles []string) error {
	if err := checkLength(line, eles, 5); err != nil {
		return err
	}
	adj := convert.linew * convert.unit * 0.5
	x1, err := parseFloatCell(eles[1], line)
	if err != nil {
		return err
	}
	x2, err := parseFloatCell(eles[2], line)
	if err != nil {
		return err
	}
	x3, err := parseFloatCell(eles[3], line)
	if err != nil {
		return err
	}
	x4, err := parseFloatCell(eles[4], line)
	if err != nil {
		return err
	}
	a, b, c, d := x1*convert.unit, x2*convert.unit, x3*convert.unit, x4*convert.unit

	convert.pdf.Line(a, b+adj, c+adj*2, b+adj)
	convert.pdf.Line(a+adj, b, a+adj, d+adj*2)
	convert.pdf.Line(a, d+adj, c+adj*2, d+adj)
	convert.pdf.Line(c+adj, b, c+adj, d+adj*2)
	return nil
}

func (convert *Converter) Image(line string, elements []string) error {
	if err := checkLength(line, elements, 6); err != nil {
		return err
	}
	x0, err := parseFloatCell(elements[2], line)
	if err != nil {
		return err
	}
	y0, err := parseFloatCell(elements[3], line)
	if err != nil {
		return err
	}
	x1, err := parseFloatCell(elements[4], line)
	if err != nil {
		return err
	}
	y1, err := parseFloatCell(elements[5], line)
	if err != nil {
		return err
	}
	r := new(gopdf.Rect)
	r.W = x1*convert.unit - x0*convert.unit
	r.H = y1*convert.unit - y0*convert.unit

	if err := convert.pdf.Image(elements[1], x0*convert.unit, y0*convert.unit, r); err != nil {
		return fmt.Errorf("%w; line %s", err, line)
	}
	return nil
}

func (convert *Converter) Line(line string, elements []string) error {
	switch elements[0] {
	case "L":
		if err := checkLength(line, elements, 5); err != nil {
			return err
		}
		p := make([]float64, 4)
		for i := 0; i < 4; i++ {
			v, err := parseFloatCell(elements[1+i], line)
			if err != nil {
				return err
			}
			p[i] = v * convert.unit
		}
		convert.pdf.Line(p[0], p[1], p[2], p[3])
	case "LH":
		if err := checkLength(line, elements, 4); err != nil {
			return err
		}
		a, err := parseFloatCell(elements[1], line)
		if err != nil {
			return err
		}
		b, err := parseFloatCell(elements[2], line)
		if err != nil {
			return err
		}
		c, err := parseFloatCell(elements[3], line)
		if err != nil {
			return err
		}
		a, b, c = a*convert.unit, b*convert.unit, c*convert.unit
		convert.pdf.Line(a, b, c, b)
	case "LV":
		if err := checkLength(line, elements, 4); err != nil {
			return err
		}
		a, err := parseFloatCell(elements[1], line)
		if err != nil {
			return err
		}
		b, err := parseFloatCell(elements[2], line)
		if err != nil {
			return err
		}
		d, err := parseFloatCell(elements[3], line)
		if err != nil {
			return err
		}
		a, b, d = a*convert.unit, b*convert.unit, d*convert.unit
		convert.pdf.Line(a, b, a, d)
	case "LT":
		if err := checkLength(line, elements, 3); err != nil {
			return err
		}
		lineType := elements[1]
		if lineType == "" {
			lineType = "straight"
		}
		convert.pdf.SetLineType(lineType)
		w, err := parseFloatCell(elements[2], line)
		if err != nil {
			return err
		}
		convert.linew = w
		convert.pdf.SetLineWidth(convert.linew * convert.unit)
	}
	return nil
}

func (convert *Converter) Cell(line string, elements []string) error {
	switch elements[0] {
	case "C":
		if err := checkLength(line, elements, 6); err != nil {
			return err
		}
		size, err := parseIntCell(elements[2], line)
		if err != nil {
			return err
		}
		if err := convert.pdf.SetFont(elements[1], "", size); err != nil {
			return fmt.Errorf("%w; line %s", err, line)
		}
		if err := convert.setPosition(elements[3], elements[4], line); err != nil {
			return err
		}
		if err := convert.pdf.Text(elements[5]); err != nil {
			return fmt.Errorf("%w; line %s", err, line)
		}
	case "CL":
		if err := checkLength(line, elements, 4); err != nil {
			return err
		}
		if err := convert.setPosition(elements[1], elements[2], line); err != nil {
			return err
		}
		if err := convert.pdf.Text(elements[3]); err != nil {
			return fmt.Errorf("%w; line %s", err, line)
		}
	case "CR":
		if err := checkLength(line, elements, 5); err != nil {
			return err
		}
		tw, err := convert.pdf.MeasureTextWidth(elements[4])
		if err != nil {
			return fmt.Errorf("%w; line %s", err, line)
		}
		xv, err := parseFloatCell(elements[1], line)
		if err != nil {
			return err
		}
		yv, err := parseFloatCell(elements[2], line)
		if err != nil {
			return err
		}
		wv, err := parseFloatCell(elements[3], line)
		if err != nil {
			return err
		}
		x := xv * convert.unit
		y := yv * convert.unit
		w := wv * convert.unit
		finalx := x + w - tw
		convert.pdf.SetX(finalx)
		convert.pdf.SetY(y)
		if err := convert.pdf.Text(elements[4]); err != nil {
			return fmt.Errorf("%w; line %s", err, line)
		}
	}
	return nil
}

func (convert *Converter) setPosition(x string, y string, line string) error {
	xv, err := parseFloatCell(x, line)
	if err != nil {
		return err
	}
	yv, err := parseFloatCell(y, line)
	if err != nil {
		return err
	}
	convert.pdf.SetX(xv * convert.unit)
	convert.pdf.SetY(yv * convert.unit)
	return nil
}

func (convert *Converter) ExternalLink(line string, elements []string) error {
	if err := checkLength(line, elements, 7); err != nil {
		return err
	}

	xv, err := parseFloatCell(elements[1], line)
	if err != nil {
		return err
	}
	yv, err := parseFloatCell(elements[2], line)
	if err != nil {
		return err
	}
	wv, err := parseFloatCell(elements[3], line)
	if err != nil {
		return err
	}
	hv, err := parseFloatCell(elements[4], line)
	if err != nil {
		return err
	}
	x, y := xv, yv
	w, h := wv, hv

	convert.pdf.SetX(x)
	convert.pdf.SetY(y)

	if err := convert.pdf.Text(elements[5]); err != nil {
		return fmt.Errorf("%w; line %s", err, line)
	}
	y1 := y
	if y-h > 0 {
		y1 = y - h
	}
	convert.pdf.AddExternalLink(elements[6], x, y1, w, h)

	convert.pdf.SetX(x + w)
	convert.pdf.SetY(y)
	return nil
}

func (convert *Converter) InternalLinkAnchor(line string, elements []string) error {
	if err := checkLength(line, elements, 7); err != nil {
		return err
	}

	xv, err := parseFloatCell(elements[1], line)
	if err != nil {
		return err
	}
	yv, err := parseFloatCell(elements[2], line)
	if err != nil {
		return err
	}
	wv, err := parseFloatCell(elements[3], line)
	if err != nil {
		return err
	}
	hv, err := parseFloatCell(elements[4], line)
	if err != nil {
		return err
	}
	x, y := xv, yv
	w, h := wv, hv
	convert.pdf.SetX(x)
	convert.pdf.SetY(y)

	if err := convert.pdf.Text(elements[5]); err != nil {
		return fmt.Errorf("%w; line %s", err, line)
	}
	y1 := y
	if y-h > 0 {
		y1 = y - h
	}
	convert.pdf.AddInternalLink(elements[6], x, y1, w, h)

	convert.pdf.SetX(x + w)
	convert.pdf.SetY(y)
	return nil
}

func (convert *Converter) InternalLinkLink(line string, elements []string) error {
	if err := checkLength(line, elements, 6); err != nil {
		return err
	}
	xv, err := parseFloatCell(elements[1], line)
	if err != nil {
		return err
	}
	yv, err := parseFloatCell(elements[2], line)
	if err != nil {
		return err
	}
	wv, err := parseFloatCell(elements[3], line)
	if err != nil {
		return err
	}
	convert.pdf.SetX(xv)
	convert.pdf.SetY(yv)

	if err := convert.pdf.Text(elements[4]); err != nil {
		return fmt.Errorf("%w; line %s", err, line)
	}
	convert.pdf.SetAnchor(elements[5])

	convert.pdf.SetX(xv + wv)
	convert.pdf.SetY(yv)
	return nil
}

func (convert *Converter) Margin(line string, eles []string) error {
	if err := checkLength(line, eles, 3); err != nil {
		return err
	}
	top, err := parseFloatCell(eles[1], line)
	if err != nil {
		return err
	}
	left, err := parseFloatCell(eles[2], line)
	if err != nil {
		return err
	}
	if top != 0.0 {
		convert.pdf.SetTopMargin(top)
	}

	if left != 0.0 {
		convert.pdf.SetLeftMargin(left)
	}
	return nil
}

func (convert *Converter) GetXY() (x, y float64) {
	return convert.pdf.GetX(), convert.pdf.GetY()
}

func (convert *Converter) MeasureTextWidth(text string) float64 {
	w, err := convert.pdf.MeasureTextWidth(text)
	if err != nil {
		panic(err)
	}

	return w
}

func (convert *Converter) SetFont(family, style string, size int) {
	err := convert.pdf.SetFont(family, style, size)
	if err != nil {
		panic(err.Error())
	}
}

func (convert *Converter) NoCompression() {
	convert.pdf.SetNoCompression()
}

func (convert *Converter) WritePdf(filepath string) error {
	return convert.pdf.WritePdf(filepath)
}

func (convert *Converter) CompressLevel(level int) {
	convert.pdf.SetCompressLevel(level)
}

func (convert *Converter) GetBytesPdf() (ret []byte) {
	return convert.pdf.GetBytesPdf()
}

func (convert *Converter) CleanupTempFonts() {
	for _, filePath := range convert.tempFonts {
		err := os.Remove(filePath)
		if err != nil {
			fmt.Printf("Warning: failed to remove temp font file %s: %v\n", filePath, err)
		}
	}
	convert.tempFonts = nil
}

func checkLength(line string, eles []string, no int) error {
	if len(eles) < no {
		return fmt.Errorf("column short: %s", line)
	}
	return nil
}

func parseIntCell(num string, line string) (int, error) {
	i, err := strconv.Atoi(num)
	if err != nil {
		return 0, fmt.Errorf("%q not integer: %s", num, line)
	}
	return i, nil
}

func parseFloatCell(num string, line string) (float64, error) {
	if num == "" {
		return 0, nil
	}
	f, err := strconv.ParseFloat(num, 64)
	if err != nil {
		return 0, fmt.Errorf("%q not numeric: %s", num, line)
	}
	return f, nil
}
